PRMT-1436 [KV/JG] Restructure repo to allow for multiple terraform stacks

diff --git a/tasks b/tasks
--- a/tasks
+++ b/tasks
@@ -2,74 +2,91 @@
 
 set -Eeo pipefail
 
-stack_name=data-sandbox
-tf_dir=terraform
-aws_region="eu-west-2"
-state_lock_table="prm-gp2gp-terraform-table"
-state_bucket="prm-gp2gp-terraform-state"
-
-function tf_init {
-
-    stack_env=$1
-
-    s3_state_key=${stack_env}/${stack_name}/terraform.tfstate
-
-    rm -rf .terraform
-
-    terraform init \
-        -backend-config key=${s3_state_key} \
-        -backend-config bucket=${state_bucket} \
-        -backend-config dynamodb_table=${state_lock_table} \
-        -backend-config region=${aws_region} \
-        ${tf_dir}
-}
-
-if [ "$#" -lt 1 ]; then
-    echo "Usage: $0 TASK [STACK-ENVIRONMENT]"
-    exit 1
+if [ "$#" -ne 3 ]; then
+  echo "Usage: $0 TASK STACK STACK-ENVIRONMENT"
+  exit 1
 fi
 
 task="$1"
+stack_name="$2"
+stack_env="$3"
+state_region="eu-west-2"
+tf_dir=stacks/${stack_name}/terraform
+env_name=$(jq -r .${stack_env}.name environment.json)
+state_lock_table=$(jq -r .${stack_env}.dynamo_table environment.json)
+state_bucket=$(jq -r .${stack_env}.bucket_name environment.json)
+s3_state_key=$(jq -r .${stack_env}.state_key_prefix environment.json)${stack_name}/terraform.tfstate
+
+function assume_role() {
+  role_arn_param=$(jq -r .${stack_env}.role_arn_param environment.json)
+  if [ "$role_arn_param" != "null" ]; then
+    role_arn=$(aws ssm get-parameters --region ${state_region} --names ${role_arn_param} --query 'Parameters[0].Value' --output text)
+    session_name="registrations-dashboard-${env_name}-session"
+
+    sts=$(
+      aws sts assume-role \
+        --role-arn $role_arn \
+        --role-session-name $session_name \
+        --output json
+    )
+
+    export AWS_ACCESS_KEY_ID=$(echo $sts | jq -r .Credentials.AccessKeyId)
+    export AWS_SECRET_ACCESS_KEY=$(echo $sts | jq -r .Credentials.SecretAccessKey)
+    export AWS_SESSION_TOKEN=$(echo $sts | jq -r .Credentials.SessionToken)
+  fi
+
+}
+
+export TF_DATA_DIR=.terraform/${stack_env}/${stack_name}
+
+function tf_init() {
+  assume_role
+  terraform init \
+    -backend-config key=${s3_state_key} \
+    -backend-config bucket=${state_bucket} \
+    -backend-config dynamodb_table=${state_lock_table} \
+    -backend-config region=${state_region} \
+    ${tf_dir}
+}
 
 echo "--- ${task} ---"
 case "${task}" in
-    validate)
-        stack_env="$2"
-        tf_init $stack_env
-        terraform validate ${tf_dir}
-    ;;
-    dojo-validate)
-        stack_env="$2"
-        dojo "./tasks validate ${stack_env}"
-    ;;
-    plan)
-        stack_env="$2"
-        tf_init $stack_env
-        terraform plan \
-            -var environment=${stack_env} \
-            -var-file=${stack_env}.tfvars \
-            -out=${stack_env}.tfplan ${tf_dir}
-    ;;
-    dojo-plan)
-        stack_env="$2"
-        dojo "./tasks plan ${stack_env}"
-    ;;
-    apply)
-        stack_env="$2"
-        tf_init $stack_env
-        terraform apply ${stack_env}.tfplan
-    ;;
-    dojo-apply)
-        stack_env="$2"
-        dojo "./tasks apply ${stack_env}"
-    ;;
-    format)
-        terraform fmt terraform
-    ;;
-    *)
-        echo "Invalid task: '${task}'"
-        exit 1
-    ;;
+validate)
+  tf_init
+  terraform validate ${tf_dir}
+  ;;
+dojo-validate)
+  dojo "./tasks validate ${stack_name} ${stack_env}"
+  ;;
+plan)
+  tf_init
+  terraform plan -var environment=$env_name \
+    -var-file=stacks/${stack_name}/vars/${stack_env}.tfvars \
+    -out=${stack_env}.tfplan ${tf_dir}
+  ;;
+dojo-plan)
+  dojo "./tasks plan ${stack_name} ${stack_env}"
+  ;;
+apply)
+  tf_init
+  terraform apply ${stack_env}.tfplan
+  ;;
+dojo-apply)
+  dojo "./tasks apply ${stack_name} ${stack_env}"
+  ;;
+format)
+  terraform fmt stacks/${stack_name}/terraform
+  ;;
+destroy)
+  tf_init
+  terraform destroy -var environment=$env_name \
+    -var-file=stacks/${stack_name}/vars/${stack_env}.tfvars \
+    ${tf_dir}
+  ;;
+*)
+  echo "Invalid task: '${task}'"
+  exit 1
+  ;;
 esac
 
 set +e
